image: 
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-python.python
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
tasks:
  - name: install-dependencies 
    init: |
      pip install -r requirements.txt
  - name: Initialize Database
    init: |
      psql -c 'CREATE DATABASE take_a_hike;'
      psql -d take_a_hike -f /workspace/take-a-hike/schema.sql
    command: echo "Database initialized"

ports:
  - name: postgreSQL
    port: 5432
    onOpen: ignore
